// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: address_book.proto

/*
Package test is a generated protocol buffer package.

It is generated from these files:
	address_book.proto

It has these top-level messages:
	Person
	AddressBook
	APIError
*/
package test

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Person_PhoneType int32

const (
	Person_MOBILE Person_PhoneType = 0
	Person_HOME   Person_PhoneType = 1
	Person_WORK   Person_PhoneType = 2
)

var Person_PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}
var Person_PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x Person_PhoneType) String() string {
	return proto.EnumName(Person_PhoneType_name, int32(x))
}
func (Person_PhoneType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorAddressBook, []int{0, 0}
}

type Person struct {
	Name   string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id     int32                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Email  string                `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phones []*Person_PhoneNumber `protobuf:"bytes,4,rep,name=phones" json:"phones,omitempty"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptorAddressBook, []int{0} }

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Person) GetPhones() []*Person_PhoneNumber {
	if m != nil {
		return m.Phones
	}
	return nil
}

type Person_PhoneNumber struct {
	Number string           `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Type   Person_PhoneType `protobuf:"varint,2,opt,name=type,proto3,enum=test.Person_PhoneType" json:"type,omitempty"`
}

func (m *Person_PhoneNumber) Reset()                    { *m = Person_PhoneNumber{} }
func (m *Person_PhoneNumber) String() string            { return proto.CompactTextString(m) }
func (*Person_PhoneNumber) ProtoMessage()               {}
func (*Person_PhoneNumber) Descriptor() ([]byte, []int) { return fileDescriptorAddressBook, []int{0, 0} }

func (m *Person_PhoneNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Person_PhoneNumber) GetType() Person_PhoneType {
	if m != nil {
		return m.Type
	}
	return Person_MOBILE
}

type AddressBook struct {
	People []*Person `protobuf:"bytes,1,rep,name=people" json:"people,omitempty"`
}

func (m *AddressBook) Reset()                    { *m = AddressBook{} }
func (m *AddressBook) String() string            { return proto.CompactTextString(m) }
func (*AddressBook) ProtoMessage()               {}
func (*AddressBook) Descriptor() ([]byte, []int) { return fileDescriptorAddressBook, []int{1} }

func (m *AddressBook) GetPeople() []*Person {
	if m != nil {
		return m.People
	}
	return nil
}

type APIError struct {
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code    int32  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (m *APIError) Reset()                    { *m = APIError{} }
func (m *APIError) String() string            { return proto.CompactTextString(m) }
func (*APIError) ProtoMessage()               {}
func (*APIError) Descriptor() ([]byte, []int) { return fileDescriptorAddressBook, []int{2} }

func (m *APIError) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *APIError) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func init() {
	proto.RegisterType((*Person)(nil), "test.Person")
	proto.RegisterType((*Person_PhoneNumber)(nil), "test.Person.PhoneNumber")
	proto.RegisterType((*AddressBook)(nil), "test.AddressBook")
	proto.RegisterType((*APIError)(nil), "test.APIError")
	proto.RegisterEnum("test.Person_PhoneType", Person_PhoneType_name, Person_PhoneType_value)
}

func init() { proto.RegisterFile("address_book.proto", fileDescriptorAddressBook) }

var fileDescriptorAddressBook = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x4d, 0x9a, 0xae, 0xed, 0x54, 0x4a, 0x19, 0xa4, 0x2c, 0x9e, 0x4a, 0xf0, 0x50, 0x14,
	0x82, 0xb4, 0x17, 0xaf, 0x2d, 0x04, 0x2c, 0x5a, 0x13, 0x17, 0xc1, 0xa3, 0x24, 0x66, 0xd0, 0xd0,
	0x26, 0xbb, 0xec, 0xc6, 0x43, 0xff, 0xb7, 0x3f, 0x40, 0x76, 0x93, 0x4a, 0xc1, 0xdb, 0x7b, 0x3b,
	0x8f, 0x37, 0x3b, 0x1f, 0x60, 0x56, 0x14, 0x9a, 0x8c, 0x79, 0xcf, 0xa5, 0xdc, 0x45, 0x4a, 0xcb,
	0x46, 0x62, 0xd0, 0x90, 0x69, 0xc2, 0x1f, 0x0f, 0x58, 0x4a, 0xda, 0xc8, 0x1a, 0x11, 0x82, 0x3a,
	0xab, 0x88, 0x7b, 0x33, 0x6f, 0x3e, 0x14, 0x4e, 0xe3, 0x18, 0xfc, 0xb2, 0xe0, 0xfe, 0xcc, 0x9b,
	0xf7, 0x85, 0x5f, 0x16, 0x78, 0x09, 0x7d, 0xaa, 0xb2, 0x72, 0xcf, 0x7b, 0x2e, 0xd4, 0x1a, 0xbc,
	0x03, 0xa6, 0xbe, 0x64, 0x4d, 0x86, 0x07, 0xb3, 0xde, 0x7c, 0xb4, 0xe0, 0x91, 0xed, 0x8e, 0xda,
	0xde, 0x28, 0xb5, 0xa3, 0xe7, 0xef, 0x2a, 0x27, 0x2d, 0xba, 0xdc, 0xd5, 0x0b, 0x8c, 0x4e, 0x9e,
	0x71, 0x0a, 0xac, 0x76, 0xaa, 0x5b, 0xde, 0x39, 0xbc, 0x81, 0xa0, 0x39, 0x28, 0x72, 0x1f, 0x18,
	0x2f, 0xa6, 0xff, 0x6b, 0x5f, 0x0f, 0x8a, 0x84, 0xcb, 0x84, 0xb7, 0x30, 0xfc, 0x7b, 0x42, 0x00,
	0xb6, 0x4d, 0xd6, 0x9b, 0xa7, 0x78, 0x72, 0x86, 0x03, 0x08, 0x1e, 0x92, 0x6d, 0x3c, 0xf1, 0xac,
	0x7a, 0x4b, 0xc4, 0xe3, 0xc4, 0x0f, 0x97, 0x30, 0x5a, 0xb5, 0x48, 0xd6, 0x52, 0xee, 0xf0, 0x1a,
	0x98, 0x22, 0xa9, 0xf6, 0xf6, 0x78, 0x7b, 0xc0, 0xc5, 0xe9, 0x26, 0xd1, 0xcd, 0xc2, 0x7b, 0x18,
	0xac, 0xd2, 0x4d, 0xac, 0xb5, 0xd4, 0xc8, 0xe1, 0xbc, 0x22, 0x63, 0xb2, 0xcf, 0x23, 0xaf, 0xa3,
	0xb5, 0x18, 0x3f, 0x64, 0x41, 0x1d, 0x34, 0xa7, 0x73, 0xe6, 0x90, 0x2f, 0x7f, 0x03, 0x00, 0x00,
	0xff, 0xff, 0xef, 0x0f, 0xe8, 0x80, 0x88, 0x01, 0x00, 0x00,
}
